### ISSUE TITLE
Error in Downloading Pretained ResNet-50 weights

### ISSUE THREAD

**Issue by Omgix** [ZJULearning/CariFaceParsing#4]
I run the command

```
python test.py --dataset cari --model psp --backbone resnet50 --aux --eval --resume=runs/helen/psp/default/model_best.pth.tar
```

Then get an error message

```
Model file is not found. Downloading.
Downloading /home/zhong/.encoding/models/resnet50-ebb6acbb.zip from https://hangzh.s3.amazonaws.com/encoding/models/resnet50-ebb6acbb.zip...
Traceback (most recent call last):
  File "test.py", line 160, in <module>
    test(args)
  File "test.py", line 71, in test
    se_loss = args.se_loss)
  File "/home/zhong/workspace/CariFaceParsing/Segmentation/encoding/models/__init__.py", line 16, in get_segmentation_model
    return models[name.lower()](**kwargs)
  File "/home/zhong/workspace/CariFaceParsing/Segmentation/encoding/models/psp.py", line 65, in get_psp
    model = PSP(num_channels, datasets[dataset.lower()].NUM_CLASS, backbone=backbone, root=root, **kwargs)
  File "/home/zhong/workspace/CariFaceParsing/Segmentation/encoding/models/psp.py", line 19, in __init__
    super(PSP, self).__init__(nclass, backbone, aux, se_loss, norm_layer=norm_layer, **kwargs)
  File "/home/zhong/workspace/CariFaceParsing/Segmentation/encoding/models/base.py", line 41, in __init__
    norm_layer=norm_layer, root=root)
  File "/home/zhong/workspace/CariFaceParsing/Segmentation/encoding/dilated/resnet.py", line 295, in resnet50
    get_model_file('resnet50', root=root)), strict=False)
  File "/home/zhong/workspace/CariFaceParsing/Segmentation/encoding/models/model_store.py", line 84, in get_model_file
    overwrite=True)
  File "/home/zhong/workspace/CariFaceParsing/Segmentation/encoding/utils/files.py", line 58, in download
    raise RuntimeError("Failed downloading url %s"%url)
RuntimeError: Failed downloading url https://hangzh.s3.amazonaws.com/encoding/models/resnet50-ebb6acbb.zip
```

**Comment by xinxxx0124** [comment]
do you solve this problem?
